### ISSUE TITLE
A few questions?

### ISSUE THREAD

**Issue by oscartbeaumont** [852Kerfunkle/kernel_zte_bladev7plus#1]
I came across this project in my research about rooting my ZTE Blade V7 and I have a few questions.
1) Does this have everything working (camera, WiFi, Bluetooth, etc)
2) What version of android is this
3) If so for the first how to go about installing it to my phone as I am new to rooting.

**Comment by 852Kerfunkle** [comment]
Hi,

please see here: https://forum.xda-developers.com/android/development/rom-lineageos-14-1-zte-blade-v7-t3785514

Please not that the build offered for download is quite outdated and ideally you would have to build it yourself. See build instructions here: https://github.com/852Kerfunkle/android_device_zte_bladev7/blob/master/manual

Cheers
